import React, { useEffect, useState } from 'react';
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  TouchableOpacity,
  Alert,
} from 'react-native';
import * as Clipboard from 'expo-clipboard';
import { Ionicons } from '@expo/vector-icons';
import { useAnalyticsStore } from '../../store/analytics.store';
import * as Sharing from 'expo-sharing';

interface SimpleReportsScreenProps {
  route: {
    params: {
      projectId: string;
    };
  };
}

export const SimpleReportsScreen: React.FC<SimpleReportsScreenProps> = ({ route }) => {
  const { projectId } = route.params;
  const [generating, setGenerating] = useState<string | null>(null);
  
  const { dashboardData, fetchDashboardData, isLoading } = useAnalyticsStore();

  useEffect(() => {
    if (!dashboardData) {
      fetchDashboardData(projectId);
    }
  }, [projectId]);

  const generateReport = async (type: 'owner' | 'contractor' | 'daily' | 'weekly') => {
    if (!dashboardData) return;
    
    setGenerating(type);
    
    try {
      const report = getReportContent(type);
      await Clipboard.setStringAsync(report);
      
      Alert.alert(
        'Report Ready! 📱',
        'Report copied to clipboard. You can now paste it in WhatsApp, SMS, or Email.',
        [
          { text: 'OK' },
          { 
            text: 'Share Report', 
            onPress: () => shareReport(report, type)
          }
        ]
      );
    } catch (error) {
      Alert.alert('Error', 'Failed to generate report');
    } finally {
      setGenerating(null);
    }
  };

  const shareReport = async (report: string, type: string) => {
    try {
      if (await Sharing.isAvailableAsync()) {
        // Create a simple text file
        const reportTitle = `${dashboardData?.project.name}_${type}_report.txt`;
        // For simplicity, we'll just show the report text
        Alert.alert('Share Report', report);
      }
    } catch (error) {
      console.error('Share error:', error);
    }
  };

  const getReportContent = (type: 'owner' | 'contractor' | 'daily' | 'weekly'): string => {
    if (!dashboardData) return '';
    
    const project = dashboardData.project;
    const metrics = dashboardData.metrics;
    const healthScore = getProjectHealthScore();
    const budgetUsed = metrics.budgetUtilization;
    const workComplete = Math.round((metrics.completedMilestones / metrics.totalMilestones) * 100);
    const today = new Date().toLocaleDateString('en-IN');

    switch (type) {
      case 'owner':
        return `🏗️ *PROJECT STATUS REPORT*
📅 Date: ${today}

*${project.name}*
━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📊 *OVERALL HEALTH: ${healthScore}/100*
${healthScore >= 80 ? '🟢 EXCELLENT' : healthScore >= 60 ? '🟡 GOOD' : '🔴 NEEDS ATTENTION'}

💰 *FINANCIAL STATUS:*
• Total Budget: ₹${(project.budget / 100000).toFixed(1)} Lakhs
• Amount Spent: ₹${(metrics.totalSpent / 100000).toFixed(1)} Lakhs
• Budget Used: ${budgetUsed}%
• Remaining: ₹${((project.budget - metrics.totalSpent) / 100000).toFixed(1)} Lakhs
${budgetUsed <= 70 ? '🟢 On Track' : budgetUsed <= 85 ? '🟡 Monitor Closely' : '🔴 Over Budget Alert'}

🎯 *WORK PROGRESS:*
• Project Completion: ${workComplete}%
• Milestones Completed: ${metrics.completedMilestones}/${metrics.totalMilestones}
• Work Updates: ${metrics.progressUpdates} this month
${workComplete >= 80 ? '🟢 On Schedule' : workComplete >= 60 ? '🟡 Minor Delays' : '🔴 Significant Delays'}

👥 *TEAM STATUS:*
• Team Size: ${metrics.teamMembers} members
• Daily Updates: Regular
• Pending Approvals: ${metrics.pendingApprovals}

📈 *RECOMMENDATION:*
${healthScore >= 80 ? '✅ Project is running smoothly. Continue current approach.' : 
  healthScore >= 60 ? '⚠️ Monitor budget and timeline closely. Minor adjustments needed.' : 
  '🚨 Immediate attention required. Review budget and timeline.'}

📱 Generated by ProjectEye
━━━━━━━━━━━━━━━━━━━━━━━━━━━━`;

      case 'contractor':
        return `🔨 *CONTRACTOR REPORT*
📅 ${today}

*Project: ${project.name}*

💼 *PAYMENT STATUS:*
• Total Work Value: ₹${(metrics.totalSpent / 100000).toFixed(1)} Lakhs
• Pending Payments: ${metrics.pendingApprovals} bills
• Work Completed: ${workComplete}%

🎯 *WORK STATUS:*
• Current Milestone: ${metrics.totalMilestones - metrics.completedMilestones} pending
• Daily Progress: Active
• Team Working: ${metrics.teamMembers} people

📋 *NEXT ACTIONS:*
• Submit daily work photos
• Complete pending milestones
• Maintain quality standards

📱 ProjectEye Report`;

      case 'daily':
        return `📅 *DAILY WORK REPORT*
Date: ${today}

*${project.name}*

👷 *TODAY'S WORK:*
• Team Present: ${metrics.teamMembers} members
• Work Status: In Progress
• Weather: Good

💰 *EXPENSES TODAY:*
• Materials: ₹_____
• Labor: ₹_____
• Other: ₹_____

📸 *PHOTOS:* Uploaded
🎯 *TOMORROW'S PLAN:* Continue work

📱 Sent via ProjectEye`;

      case 'weekly':
        return `📊 *WEEKLY SUMMARY*
Week ending: ${today}

*${project.name}*

🎯 *WEEK'S PROGRESS:*
• Work Completed: ${workComplete}%
• Budget Used: ${budgetUsed}%
• Team Performance: Good

💰 *WEEKLY EXPENSES:*
• Total Spent: ₹${(metrics.totalSpent / 100000).toFixed(1)} Lakhs
• Major Items: Materials, Labor

📈 *NEXT WEEK TARGET:*
• Complete pending milestones
• Monitor budget usage
• Maintain work quality

🚨 *ALERTS:*
${budgetUsed > 85 ? '⚠️ Budget usage high' : '✅ Budget on track'}
${workComplete < 60 ? '⚠️ Work progress slow' : '✅ Good progress'}

📱 ProjectEye Weekly Report`;

      default:
        return '';
    }
  };

  const getProjectHealthScore = () => {
    if (!dashboardData) return 0;
    
    const budgetScore = Math.max(0, 100 - dashboardData.metrics.budgetUtilization);
    const milestoneScore = dashboardData.metrics.totalMilestones > 0 
      ? (dashboardData.metrics.completedMilestones / dashboardData.metrics.totalMilestones) * 100 
      : 100;
    const progressScore = dashboardData.metrics.progressUpdates > 0 ? 100 : 50;
    
    return Math.round((budgetScore * 0.4 + milestoneScore * 0.4 + progressScore * 0.2));
  };

  const renderReportCard = (
    title: string,
    description: string,
    type: 'owner' | 'contractor' | 'daily' | 'weekly',
    icon: keyof typeof Ionicons.glyphMap,
    color: string
  ) => (
    <TouchableOpacity 
      style={[styles.reportCard, { borderLeftColor: color }]}
      onPress={() => generateReport(type)}
      disabled={generating !== null}
    >
      <View style={styles.reportCardHeader}>
        <View style={[styles.reportCardIcon, { backgroundColor: `${color}20` }]}>
          <Ionicons name={icon} size={28} color={color} />
        </View>
        <View style={styles.reportCardTitles}>
          <Text style={styles.reportCardTitle}>{title}</Text>
        </View>
      </View>
      
      <Text style={styles.reportCardDescription}>{description}</Text>
      
      <View style={styles.reportCardFooter}>
        {generating === type ? (
          <View style={styles.generatingContainer}>
            <Text style={styles.generatingText}>Preparing Report...</Text>
          </View>
        ) : (
          <View style={styles.shareOptions}>
            <View style={styles.shareOption}>
              <Ionicons name="logo-whatsapp" size={16} color="#25D366" />
              <Text style={styles.shareOptionText}>WhatsApp</Text>
            </View>
            <View style={styles.shareOption}>
              <Ionicons name="mail" size={16} color="#3B82F6" />
              <Text style={styles.shareOptionText}>Email</Text>
            </View>
            <View style={styles.shareOption}>
              <Ionicons name="chatbubbles" size={16} color="#6366F1" />
              <Text style={styles.shareOptionText}>SMS</Text>
            </View>
          </View>
        )}
      </View>
    </TouchableOpacity>
  );

  if (isLoading) {
    return (
      <View style={styles.loadingContainer}>
        <Text style={styles.loadingText}>Loading Reports...</Text>
      </View>
    );
  }

  return (
    <ScrollView style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Project Reports</Text>
        <Text style={styles.headerSubtitle}>Simple reports for WhatsApp, SMS & Email</Text>
      </View>

      <View style={styles.reportsContainer}>
        {renderReportCard(
          'Owner Report',
          'Complete project status for project owners and investors',
          'owner',
          'business',
          '#3B82F6'
        )}

        {renderReportCard(
          'Contractor Report',
          'Work progress and payment status for contractors',
          'contractor',
          'hammer',
          '#10B981'
        )}

        {renderReportCard(
          'Daily Work Report',
          'Daily work summary for team communication',
          'daily',
          'today',
          '#F59E0B'
        )}

        {renderReportCard(
          'Weekly Summary',
          'Weekly progress summary for stakeholders',
          'weekly',
          'calendar',
          '#8B5CF6'
        )}
      </View>

      <View style={styles.tipsContainer}>
        <Text style={styles.tipsTitle}>💡 Quick Tips</Text>
        <Text style={styles.tipsText}>• Reports are automatically copied to clipboard</Text>
        <Text style={styles.tipsText}>• Perfect for WhatsApp groups and SMS</Text>
        <Text style={styles.tipsText}>• Share with team members instantly</Text>
        <Text style={styles.tipsText}>• Professional format with emojis</Text>
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#374151',
  },
  
  header: {
    backgroundColor: '#FFFFFF',
    padding: 20,
    marginBottom: 16,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1F2937',
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    marginTop: 8,
  },
  
  reportsContainer: {
    paddingHorizontal: 16,
  },
  reportCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderLeftWidth: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  reportCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  reportCardIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  reportCardTitles: {
    flex: 1,
  },
  reportCardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1F2937',
  },
  reportCardDescription: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
    marginBottom: 16,
  },
  reportCardFooter: {
    minHeight: 40,
  },
  generatingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  generatingText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#3B82F6',
  },
  shareOptions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  shareOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
  },
  shareOptionText: {
    fontSize: 12,
    color: '#6B7280',
    marginLeft: 4,
    fontWeight: '500',
  },
  
  tipsContainer: {
    backgroundColor: '#FFFFFF',
    margin: 16,
    padding: 16,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#10B981',
  },
  tipsTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 12,
  },
  tipsText: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 6,
    lineHeight: 20,
  },
});